version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - '27000:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mongo-db
    volumes:
      - mongo-db:/data/db/

volumes:
  mongo-db: